version: '3.1'

services:
  db:
   image: mongo:latest
   restart: always
   container_name: AgileOut-local-db
   ports:
    - '27017:27017'
   volumes:
    - mongodata:/data/db


volumes:
  mongodata:
