/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const EnumRoleOfUser = {
  USER: 'user',
};
const EnumTypeOfToken = {
  REFRESH: 'refresh',
};
module.exports = {
  EnumRoleOfUser,
  EnumTypeOfToken,
};
